require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native/scripts/react_native_pods'

platform :ios, '13.4'
prepare_react_native_project!

target 'MiniWalletApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
